### ISSUE TITLE
Minor readability improvement of bool

### ISSUE THREAD

**Issue by Harding-Stardust** [arizvisa/ida-minsc#162]
```return True if cls.lflags(idaapi.LFLG_IS_DLL) else False```
I would suggest changing it to:
```return bool(cls.lflags(idaapi.LFLG_IS_DLL))```
https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/base/database.py#L186

Very similar note on
https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/base/database.py#L194

**Comment by arizvisa** [comment]
The `__nonzero__` attribute implicitly converts the type to boolean, and both True/False are explicitly of the same type that you suggest reinstantiating using `bool`.  This is just an aesthetic concern, and not really an issue or bug afaict.

I'm not a language lawyer, but explicitly using `bool` results in a global name lookup (the "LOAD_GLOBAL" instruction) which has the extra side-effect that redefining `bool` can change the semantics of how this code works. This is opposed to the usage of True/False being loaded directly out of the constants. I wasn't considering it at first, but implicit boolean actually provides better code for optimization and is safer. I'd imagine the performance here is negligible, but still that's likely irrelevant since this is literally Python.

I'm not sure if this is a bug being reported or what the intent of this is. I don't generally mind, but I'm still tagging this issue as wontfix for now and will close in the future unless you have any significant objections.

**Comment by Harding-Stardust** [comment]
It was just a suggestion to make the code easier to read. You can close this issue.

**Comment by arizvisa** [comment]
Closing as requested.
