### ISSUE TITLE
Rename argument name "direction" to something better like "options"

### ISSUE THREAD

**Issue by Harding-Stardust** [arizvisa/ida-minsc#163]
The other functions have the argument named options which is a better name
here: https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/base/database.py#L1160
and here: https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/base/database.py#L1165

**Comment by arizvisa** [comment]
Yeah, actually. This usage of "direction" as the name is terrible. Generally the names that are used for keyword parameters tend to be the parameter that you're most likely to use.

i.e.
```
def decode(..., **byteorder):
   ...
```
This way when you view the help, you know that you can specify `decode(byteorder=something)`. In the example you pointed out, however, there is no `direction` parameter and the only major parameter is really `reverse`. Thus I believe that "reverse" is a actually a better name since it also implies that you'd want to give it a true/false value.

Is there any significant reason you believe that "options" is better, or is your decision strictly because you saw it elsewhere? The IDAPython API seems to only allow you to control the search direction, is there another flag that you believe should be exposed?

**Comment by Harding-Stardust** [comment]
You also have radix, encoding and flags and these are all options that you control the search behavior with.
I saw you used the name options in other functions and thought that it's a better name.
You get the hang of what argument is suppose to do from your earlier experience with the codebase.

**Comment by Harding-Stardust** [comment]
Since the direction argument can hold multiple values I suggested to call it options as you have done in database.search.iterate.
For encodings, I sometimes use (I dont have my scripts here at home so I don't really remember the name but I think it is this)
ida_nalt.get_default_encoding_idx(ida_nalt.BPU_1B) which is to search for a string with all (1 Byte Per Unit) encodings IDA knows of.
But you are correct in that I would probably use the database.search.iterate() to search for strings, I just wanted to help you set a better name in the code.

**Comment by arizvisa** [comment]
Fair enough. Closing as a non-issue in that case.
