### ISSUE TITLE
Rename go --> jumpto (since the term go usually means "let the debugger run" in RE)

### ISSUE THREAD

**Issue by Harding-Stardust** [arizvisa/ida-minsc#178]
Rename to jump or jumpto. Go in RE usually means that you let the debugger run

https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/base/database.py#L1446

**Comment by arizvisa** [comment]
Hmm.. I could add an alias for that, but the reason why it's defined as `go` is because it's short. If you're going to be typing `jump` or `jumpto`, you might as well use `idaapi.jumpto`. (You can assign the `idaapi` module to something shorter in your `.idapythonrc.py` file, or you can also tamper directly with the `database` module if you prefer it to exist over there.)

Another thing to consider is that both `go` and `goof` (`goto_offset`) are included in the default namespace that your database opens up with. They're short because it's expected that you'll want to navigate to a specific address or offset in the database fairly often. So, for the sake of symmetry `go` was chosen.

Do you have a suggestion for another name that's shorter than IDAPython's `jumpto` name that you would prefer? Something that can also be used to describe visiting an offset in the binary relative to the base address?

**Comment by Harding-Stardust** [comment]
With autocompletion the few extra characters don't really make a change when typing but if you want it short maybe name it "jmp" with an alias of "j" ?

**Comment by arizvisa** [comment]
This was added by PR #193, which was just merged into the master branch. Closing this issue as resolved. If you feel that there is more to this, feel free to re-open.
