### ISSUE TITLE
Putting files in root of IDA appdir has some issues

### ISSUE THREAD

**Issue by x0rloser** [arizvisa/ida-minsc#22]
Do the ida-minsc files need to be in the root of the IDA appdata folder?
Is it perhaps required to add in the various hooks?
Is there any way of doing it from its own subdir, such as "ida-minsc", inside the appdata dir?

Reasons:
* It makes it a bit hard to differentiate between what files in the appdata dir are ida-minsc files or what are files for other stuff.
* Similar to the above it complicates uninstall, knowing what files to remove
* When attempting to clone the git repo into the appdata dir it complains due to dir having existing files in it
* Once cloned the repo thinks that any other existing files should now be part of the repo, which isnt the case if they aren't ida-minsc specific. I know they can be added to .gitignore, but it seems a bit messy having to do so for any various files you may have. I guess you could use whitelisting style gitignore rules to instead specify all the files that *are* in the repo, so any others are ignored.
* Does the shortcut.cfg from the repo need to be included? It contains user specific shortcuts and including it will overwrite another users unique settings. Unless there is a specific reason I suggest removing it from being tracked by the repo.

**Comment by arizvisa** [comment]
Yea, the main reason why is because of those hooks. The idea is to get that `idapythonrc.py` file executed which then uses sys.meta_path to identify all the sub-directories/modules. Once all that configuration is done, then the current python namespace (globals) is replaced with the contents of `__root__.py`.

Everything could probably be shifted into its sub-directory, but it was dumbed down for my friends to install back when it was started (like 10 years ago) and has just stayed like that since then. Really, It's all about that `idapythonrc.py` needing to be executed. If you want to move ida-minsc somewhere else, you can write your own `idapythonrc.py` that will then `execfile` ida-minsc's. One of my users does something similar to that in order to use Jupyter/iPython's notebook interface instead of IDA's.

At one point I was going to write a wrapper for plugins so they could just be dropped in the plugins/ directory (I think this is similar to Sark). But since I haven't really had a need for any particular plugins while I've been reversing, it never found a need to get developed.

If you want to change the stupid install process, PRs are more than welcome. One reason why I went public with this is because I've been maintaining this amongst friends for like ever but am getting tired of working on it.

Yea, that `shortcut.cfg` probably shouldn't be there. Older versions of IDA used to use that key-binding for opening files and so when newer versions of IDA changed it, I added it to the repo since the first thing I do whenever I installed IDA is copy my `idauser.cfg`, `idauserg.cfg`, and then clone this repo.

**Comment by arizvisa** [comment]
But yeah, I'll remove that `shortcut.cfg` instead of imposing my configuration on you guys.

**Comment by arizvisa** [comment]
@x0rloser, were you able to move ida-minsc to another place and execfile its `idapythonrc.py` successfully?

**Comment by arizvisa** [comment]
Closing due to lack of response. If your issue still persists, feel free to re-open.
