### ISSUE TITLE
Question: Which versions of IDA are supported?

### ISSUE THREAD

**Issue by karlek** [arizvisa/ida-minsc#36]
The documentation states that IDA versions: 6.9 up to 7.1.180227 are supported. 
https://arizvisa.github.io/ida-minsc/install.html#software-requirements

And the contribution guidelines states that new git tags will be added on new IDA versions. 
https://github.com/arizvisa/ida-minsc/blob/master/CONTRIBUTING.md#new-versions-of-ida-tags

As far as I can see, there are no git tags on this repo, and the project is actively developed. So I wonder if newer IDA versions are supported, like 7.4?

**Comment by arizvisa** [comment]
Lol. Yeah... my bad. I haven't re-built the docs in a bit because nothing significant has really changed.

When I had tested 7.1.180227, all 3 platforms worked. All my friends however (whom I get most of my bug reports through) run it on Windows with 7.4, and they haven't pointed out anything. I can't be sure about the non-windows platforms though for 7.4 because we have all Windows licenses since that constraint.

I haven't upgraded my version of IDA since this was released because Ilfak's licensing has changed if one works for a company, which includes licensing server requirements and an explicit license per platform which makes it difficult for me to test this on absolutely everything.

Nonetheless, I \_will\_ still support this regardless. Probably till I die or stop reversing, whichever comes first.

**Comment by arizvisa** [comment]
Oh also, this whole library is essentially just a compartmentalized wrapper around `idaapi`. So unless there are major changes to the API as there was from 6.95 to 7, we should still be okay unless something in `idaapi` is broken (IDA's tech support is phenomenal though when you point out things or need to understand internals). 

The only other requirement which I forgot to list is that it's developed with Python2, and I haven't gone through that Python3 transitioning because of my hate for it. I'll add this Python2 requirement to the docs and rebuild them as a result of this insight too.

**Comment by arizvisa** [comment]
So, short answer: Yes. I will fix the bugz that you report in all versions of IDA from 5.6 and up.

**Comment by arizvisa** [comment]
This issue was addressed by PRs #39, and #40. The documentation in the `gh-pages` branch was also re-built to accommodate the addressed changes so that https://arizvisa.github.io/ida-minsc

@karlek, do these changes address your question/concerns?

**Comment by karlek** [comment]
> Lol. Yeah... my bad. I haven't re-built the docs in a bit because nothing significant has really changed.

@arizvisa No worries! This project is exactly what I've been looking for, but didn't want to get too excited before I knew if it would support my environment (which it does!). So I'm thrilled to test it out, and I'll gladly submit any bug reports if I'd encounter any.

> I haven't upgraded my version of IDA since this was released because Ilfak's licensing has changed if one works for a company, which includes licensing server requirements and an explicit license per platform which makes it difficult for me to test this on absolutely everything.

Yeah, I mainly reverse in ARM at work, and sadly we don't have a license which also covers x86 so I can't use it in my hobby projects atm.

>  Nonetheless, I _will_ still support this regardless. Probably till I die or stop reversing, whichever comes first.

I'm glad to hear it! 

> (IDA's tech support is phenomenal though when you point out things or need to understand internals).
Cool! I saw that this project was featured in their annual plugin competition, and your documentation feels more developer friendly than IDA's does. 

> The only other requirement which I forgot to list is that it's developed with Python2, and I haven't gone through that Python3 transitioning because of my hate for it.

Haha, you're not looking forward to the Python2 sunset I take it.

**Comment by arizvisa** [comment]
Awesome.

Another place to grab docs is at your IDAPython prompt with `help($whatever)`, the auto-documentation is parsed straight into the html documentation, so for quick familiarity with a particular command, you'll likely find it more useful (at least I do).

Definitely checkout the tagging component btw, it's based on some research that me and a friend did a while ago. Essentially you can attach any short python type to an address (by hijacking comments) which can help with marking something that you want to check-out, and then query them later, or even to hand a copy of your tags to another user (for collaboration). http://arizvisa.github.io/ida-minsc/modules/custom-tags.html#module-tags

Anyways, I'm going to close this issue. Thanks for your report!
